version: '3.7'

services:
  ewake:
    image: 1thorsten/ewake:1.0.12
    container_name: ewake
    network_mode: host
    restart: unless-stopped
    volumes:
      - ewake-clients:/ewake-clients
    labels:
      # value (false,all,admin)
      - docon.v1={"console":"admin","control":"all"}
volumes:
  ewake-clients:
