services:
  ewake:
    image: 1thorsten/ewake:latest
    container_name: ewake
    network_mode: host
    restart: unless-stopped
    environment:
      - EWAKE_NETWORK_INTERFACE=eth0
    volumes:
      - ewake-clients:/ewake-clients
    labels:
      # value (false,all,admin)
      - docon.v1={"console":"admin","control":"all","show":"true"}
    #ports:
    #- "5555:5555"
volumes:
  ewake-clients:
